---
title: 'Common statistical tests are linear models'
subtitle: '' # this goes below title in main post
summary: Most common statistical tests are special cases of linear regression. Viewing the linear model as a 'Swiss army knife' can foster a more intuitive understanding of statistical tests. 
author: ''
date: '2019-08-10'
slug: statistical-tests
categories: []
tags: []
authors: []
lastmod: ''
featured: false
draft: false
image:
  caption: ""
  preview_only: true
projects: []
---

For this post I wrote a short ebook exploring how [**most common statistical tests are examples of linear models**](https://steverxd.github.io/Stat_tests/).

This was adapted from, and owes credit to, a book by Jonas Lindeløv called *Common statistical tests are linear models (or: how to teach stats)* [(here)](https://lindeloev.github.io/tests-as-linear/). This book demonstrates how many common statistical tests (such as the t-test, ANOVA and chi-squared) are special cases of a linear model. 

To solidify my understanding, I worked through the examples provided in Jonas' book to expand on areas where there were gaps in my knowledge, and to explain some of the ideas using terms and concepts with which I was more familiar.

The main idea of the book is that most statistical tests can be explained as an application of the simple linear model, _$y = a + b⋅x$_,  which is familiar to most students of introductory statistics.   

This allows us to view the linear model as the 'Swiss army knife' of statistical tests. The approach brings coherence to a wide range of statistical tests, which are usually taught to students as independent tools. It helps to explain the intuition underlying statistical tests by drawing on the familiar concept of linear regression.

I hope you find this version of the book useful. 
